"""initial migration

Revision ID: 83e6dc7f88e7
Revises: 
Create Date: 2025-02-06 21:55:51.949104

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '83e6dc7f88e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('id_deck_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hand_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'hand', ['hand_id'], ['id'])

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_constraint('inventory_ibfk_2', type_='foreignkey')
        batch_op.drop_column('resourcedeck_card_id')

    with op.batch_alter_table('resource_deck_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'inventory', ['inventory_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_deck_card', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('inventory_id')

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resourcedeck_card_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('inventory_ibfk_2', 'resource_deck_card', ['resourcedeck_card_id'], ['id'])

    with op.batch_alter_table('id_deck_card', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('hand_id')

    # ### end Alembic commands ###
